version: '3'

services:
  db:
    image: mysql
    volumes:
      - resume-builder-volume:/var/lib/mysql
      - ${PWD}/database/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    env_file: .env

  backend:
    build:
      context: backend
    env_file: .env

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  resume-builder-volume:
    external: false
